# Generated by Django 4.1.7 on 2023-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.URLField(max_length=500),
        ),
    ]
