# Generated by Django 4.1.7 on 2023-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_photo_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="title",
        ),
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(max_length=101),
        ),
    ]
